apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-app-config
  namespace: default
data:
  # Frontend will automatically detect the correct URLs based on current hostname
  MYSQL_DATABASE_UA: "useraccount_db"
  MYSQL_DATABASE_TA: "transaction_db"
  JWT_ISSUER: "BankingApp"
  JWT_AUDIENCE: "UserAccountAPI"
  PROMETHEUS_PORT: "9091"
