apiVersion: v1
kind: Service
metadata:
  annotations:
    app: query-service
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: query-service
    app: query-service
  name: query-service
spec:
  type: NodePort
  ports:
    - name: "http" # Renamed from "8004" for clarity
      port: 8004
      targetPort: http # Targets the named port 'http' (8080) on the pod
      protocol: TCP
      nodePort: 30004 # External port for frontend access
  selector:
    app: query-service
