apiVersion: v1
kind: Service
metadata:
  name: user-account-service
  labels:
    app: user-account-service
spec:
  type: NodePort
  selector:
    app: user-account-service
  ports:
    - name: http
      protocol: TCP
      port: 8002 # Service port for application
      targetPort: 8080 # Container port for application (http)
      nodePort: 30002 # External port for frontend access
    - name: metrics
      protocol: TCP
      port: 9091 # Service port for metrics
      targetPort: 9091 # Container port for metrics (prometheus)
