FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
COPY UserAccountService.csproj .
RUN dotnet restore
COPY . .
EXPOSE 80 9091
CMD ["dotnet", "watch", "run", "--non-interactive", "--urls", "http://*:80"]