{
 "title": "Fraud Detection",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Duplicate Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "duplicate_messages_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fraud Detections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "fraud_detections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total processed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "messages_processed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Processing Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "processing_errors_total", "legendFormat": "__auto" }
   ]
  }
 ]
}