{
 "title": "UserAccountService Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AccountService Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "account_service_requests_total", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "AccountService Idempotent Balance Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "account_service_idempotent_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AccountService Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "account_service_errors_total", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "AccountService Successes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "account_service_successes_total",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}